[target.'cfg(target_os = "none")']
runner = "cargo run --package runner --"
rustflags = [
    "-C",
    "relocation-model=pie",
    "-C",
    "link-args=--image-base=0xffffffff80000000",
    "-C",
    "code-model=kernel",
    "-C",
    "force-frame-pointers=y",
]

[alias]
kbuild = "build --bin main --target x86_64-unknown-none -Zbuild-std=core,alloc -Zbuild-std-features=compiler-builtins-mem"
kclippy = "clippy --bin main --target x86_64-unknown-none -Zbuild-std=core,alloc -Zbuild-std-features=compiler-builtins-mem"
kimage = "run --release --bin main --target x86_64-unknown-none -Zbuild-std=core,alloc -Zbuild-std-features=compiler-builtins-mem -- --no-boot"
krun = "run --bin main --target x86_64-unknown-none -Zbuild-std=core,alloc -Zbuild-std-features=compiler-builtins-mem"
ktest = "test --package kernel --target x86_64-unknown-none -Zbuild-std=core,alloc -Zbuild-std-features=compiler-builtins-mem"

[env]
OVMF_FD = { value = "/usr/share/ovmf/OVMF.fd" }
LIMINE_PREFIX = { value = "/usr/local" }
INITRD_DIR = { value = "initrd", relative = true }
LIBC_DIR = { value = "libc", relative = true }

[unstable]
features = ["host_dep"]
