[workspace]

[package]
name = "third-party"
version = "0.0.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "1.0.0"

[lib]
name = "fake"
path = "/dev/null"
